{% set name = "anuga" %}
{% set version = "3.3.1" %}
{% set sha = "26ddd0463efbd82133f6b8ab3619651d1eaac5c3b3361ac30c5bdffb7fd5423b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anuga-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  script: {{ PYTHON }} -m pip install . --no-build-isolation -vv
  number: 0
  skip: True  # [py<3.10]

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ stdlib("c") }}      # [not win]
    - gcc_win-64             # [win]
    - gxx_win-64             # [win]

  host:
    - python
    - pip
    - cython
    - meson-python
    - ninja
    - numpy >=2.0.0
    - pybind11
    - libpython  # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - dill >=0.3.7
    - matplotlib-base >=3.7
    - meshpy >=2022.1
    - netcdf4 >=1.6
    - scipy >=1.11
    - pyproj >=3.6
    - xarray
    - libgomp  # [linux]

  run_constrained:
    - mpi4py
    - pymetis >=2023.1
    - rasterio
    - fiona
    - shapely
    - pandas
    - openpyxl

test:
  imports:
    - anuga
  commands:
    - pytest --pyargs anuga -x -q -m "not slow" -p no:warnings
  requires:
    - pytest

about:
  home: https://github.com/anuga-community/anuga_core
  summary: A set of python modules for tsunami and flood modelling
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - stoiver
