{% set name = "anuga" %}
{% set version = "3.3.7" %}
{% set sha = "c63577b6d8f3610972b24369d201b3398de77e491c631f91938efcf1d4acc63d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anuga-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  number: 0
  skip: true  # [py<3.10]
  script:
    # Parse MESON_ARGS so meson finds the right executables when cross-compiling.
    - $PYTHON -m build -w -n -x -Csetup-args=${MESON_ARGS// / -Csetup-args=}   # [unix]
    - $PYTHON -m pip install dist/anuga*.whl                                    # [unix]
    - {{ PYTHON }} -m pip install . --no-build-isolation -vv                    # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ stdlib("c") }}      # [not win]
    - gcc_win-64             # [win]
    - gxx_win-64             # [win]

  host:
    - python
    - pip
    - python-build
    - cython
    - meson-python
    - ninja
    - numpy >=2.0.0
    - pybind11
    - libpython  # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - utm
    - pyproj >=3.6
    - dill >=0.3.7
    - matplotlib-base >=3.7
    - meshpy >=2022.1
    - netcdf4 >=1.6
    - scipy >=1.11
    - xarray
    - libgomp  # [linux]

  run_constrained:
    - mpi4py
    - pymetis >=2023.1
    - affine >=2.4
    - rasterio
    - fiona
    - shapely
    - pandas
    - openpyxl

test:
  imports:
    - anuga
  commands:
    - pytest --pyargs anuga -x -q -m "not slow" -p no:warnings
  requires:
    - pytest

about:
  home: https://github.com/anuga-community/anuga_core
  summary: A set of python modules for tsunami and flood modelling
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - stoiver
